### ISSUE TITLE
Warn on large filesize?

### ISSUE THREAD

**Issue by Wowfunhappy** [ideasonpurpose/tooling-starter-pack#16]
Could we use https://www.npmjs.com/package/gulp-check-filesize to warn the user if any files are over a certain amount? For example, if any images are over 1 mb.

**Comment by joemaller** [comment]
I like this. Unfortunate that the packages haven't been updated in a long time -- though it's not a complicated action.

Considering our problem is usually uncompressed images, It might be interesting to run a lossy compression with sane defaults for comparison, then alert when the provided and re-compressed file sizes differ substantially. 

Some options:
* [gulp-check-filesize](https://www.npmjs.com/package/gulp-check-filesize)
* [gulp-warn-size](https://github.com/philmander/gulp-warn-size)
* [gulp-sizereport](https://www.npmjs.com/package/gulp-sizereport)
* [performance.maxAssetSize](https://webpack.js.org/configuration/performance/#performance-maxassetsize) (webpack)

**Comment by joemaller** [comment]
Maybe even better than file size, ImageMagick can read the compression level (`quality`) of JPEGs. We could flag anything over `70`.

https://imagemagick.org/script/identify.php


Possible log notification: 

```
[01:23:45] gulp-image-check: 'huge-img.jpg' is 800 kb with a Quality of 95.
[01:23:45] gulp-image-check: ----------------------------
[01:23:45] gulp-image-check:      25% Quality:  144 kb
[01:23:45] gulp-image-check:      40% Quality:  256 kb
[01:23:45] gulp-image-check:      60% Quality:  418 kb
[01:23:45] gulp-image-check:      80% Quality:  788 kb  
```

We could do something similar for PNGs over a certain size. Or maybe there's some metric for evaluating the effectiveness of PNGs lossless compression.

**Comment by Wowfunhappy** [comment]
This is irrelevant with #18
